apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim  # name of PVC essential for identifying the storage data
  namespace: ninja 
  labels:
    app: mongodb
    # tier: database
spec:
  accessModes:
    - ReadWriteMany   #This specifies the mode of the claim that we are trying to create.
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi    #This will tell kubernetes about the amount of space we are trying to claim.